#:schema ./schema.json
# relative schema location for ease

[interface]
tooltips = true
nerd_font = true
use_reactive_layout = true
show_progress_eta = false
show_progress_percentage = true
truncate_progress_file_path = false
show_line_numbers = true
show_hidden_files = false
allow_tab_nav = true
append_new_tabs = true
double_click_delay = 0.25
drive_watcher_frequency = 3.0
spinner = "⣾⣽⣻⢿⡿⣟⣯⣷"
# yazi style is 5
# but it has more space
scrolloff = 3

[interface.image_viewer]
protocol = "Auto"
max_size = [4000, 4000]

[interface.font_preview]
max_size = [1000, 1000]
font_size = 50

[interface.preview_text]
max_file_size = 2097152
error = "couldn't read this file! (\u00AC_\u00AC)" # ¬_¬
start = """
  ___ ___
 |  _| . |
 |_| |___|
  _ _ ___
 | | |  _|
  \\_/|_|
"""
font_text = """
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
oO08 iIlL1 g9qCQG a@ 5sS
{} [==>  ] (*) <> ~-+ /\\
"""

[interface.clock]
enabled = false
align = "left"

[interface.compact_mode]
buttons = true
panels = false

[settings]
copy_includes_metadata = true
use_recycle_bin = true

history_size = 200
# comments are just how shell config would look like, it will never be
# set as default options in the menu, it can be used as reference
right_click = [
  # { label = "\uf0b0 Open With", if = { directory = false }, options = [
  #   { label = "\ue8da VSCode", action = { run = 'code %s', run_type = "orphan" } },
  #   { label = "\ue272 Helix", action = { run = 'hx %s', run_type = "suspend" }, if = { path = ["C:/Users/notso/Git/*"] } },
  #   { label = "\ue0c6 Pixelorama", action = { run = 'pixelorama %s', run_type = "suspend" }, if = { path = ["*.png"] } },
  # ] },
  { label = "\uf0c5 Copy", options = [
    { label = "\uf07f Copy in rovr", action = "rovr:copy" },
    { label = "\U000f0147 Copy highlighted file path", action = "system:copy_highlighted" },
    { label = "\U000f0169 Copy highlighted file name", action = "system:copy_name" },
    { label = "\U000f14e5 Copy current directory path", action = "system:copy_current_directory" },
    { label = "\U000f1265 Copy to OS clipboard", action = "system:copy_to_system_clip" },
    # { label = " Copy SHA256", action = { run = 'pwsh -nop -c "(Get-FileHash -Algorithm SHA256 \"%s\").Hash | Set-Clipboard"', run_type = "background" }, if = { directory = false } }
  ] },
  { label = "\uf0c4 Cut", action = "rovr:cut" },
  { label = "\uf429 Paste", action = "rovr:paste" },
  { label = "\uea7f New", action = "rovr:new" },
  { label = "\uf246 Rename", action = "rovr:rename" },
  { label = "\uf014 Delete", action = "rovr:delete" },
  { label = "\uf410 Zip", action = "rovr:zip" },
  { label = "\uf07c Unzip", action = "rovr:unzip" },
  { label = "\uea74 Properties", action = { run = [
    "powershell",
    "-NoProfile",
    "-Command",
    "& { param([string] $cwd, [string] $name) $shell = New-Object -ComObject Shell.Application; $shell.NameSpace($cwd).ParseName($name).InvokeVerb('Properties'); Start-Sleep -Milliseconds 500; while (Get-Process | Where-Object { $_.MainWindowTitle -match ([regex]::Escape($name) + ' Properties') }) { Start-Sleep -Milliseconds 500 } }",
    "%rcwd",
    "%rnh",
  ], run_type = "background", shell = false }, if = { os = ["Windows"] } },
  # { label = " Get SHA256", action = { run = 'pwsh -nop -c "(Get-FileHash -Algorithm SHA256 \"${highlighted_file}\").Hash"', run_type = "background" }, if = { directory = false }}
]
drive_exclude = ["/var/*"]

[settings.preview_rules]
"application/(debian.*-package|redhat-package-manager|rpm|android\\.package-archive)" = "archive"
"application/(iso9660-image|qemu-disk|ms-wim|apple-diskimage)" = "archive"
"application/(rar|7z.*|tar|xz|bzip.*|lzma|compress|archive|cpio|arj|xar|ms-cab.*)" = "archive"
"application/(zip|gzip|zstd|bzip2|vnd\\.rar)" = "archive"
"application/java-archive" = "archive"
"application/virtualbox-(vhd|vhdx)" = "archive"
"application/x-(xz|tar|gzip|bzip2|xz|rar|rar-compressed|7z-compressed|zstd-compressed-tar)" = "archive"
"application/(json|javascript|xml|raml\\+yaml)" = "text"
"application/(mbox|ndjson|wine-extension-ini)" = "text"
"application/x-(yaml|script|pem-file|subrip|typescript)" = "text"
"application/vnd.openxmlformats-officedocument.wordprocessingml.document" = "remime"
"application/ms-opentype" = "font"
"application/pdf" = "pdf"
"image/svg\\+xml" = "resvg"
"inode/directory" = "folder"

"application/font-.*" = "font"
"application/x-font-.*" = "font"
"image/.*" = "image"
"text/.*" = "text"
"font/.*" = "font"

[settings.openers.groups]
# unset for the end user

[settings.openers.match]
# unset for the end user

[settings.editor.file]
run = "$EDITOR"
orphan = false

[settings.editor.folder]
run = "$EDITOR"
orphan = false

[settings.editor.bulk_editor]
rename_show_as_mapping = true
run = "$EDITOR"

[metadata]
fields = [
  "type",
  "permissions",
  "size",
  "modified",
  "accessed",
  "created",
  "hidden",
  "mime",
]
datetime_format = "%Y-%m-%d %H:%M"
filesize_decimals = 1
filesize_suffix = "decimal"

[theme]
default = "nord"
preview = "nord"
transparent = false

[keybinds]
# legacy version, vim and sane are not available.
toggle_pin = ["P"]
toggle_pinned_sidebar = ["S"]
toggle_preview_sidebar = ["I"]
toggle_footer = ["F"]
toggle_menu_wrapper = ["M"]
focus_toggle_pinned_sidebar = ["s"]
focus_file_list = ["escape"]
focus_toggle_preview_sidebar = ["i"]
focus_toggle_path_switcher = ["ctrl+l"]
focus_search = ["slash"]
focus_toggle_processes = ["#"]
focus_toggle_clipboard = ["c"]
focus_toggle_metadata = ["m"]
copy = ["y", "ctrl+c"]
paste = ["p", "ctrl+v"]
cut = ["x", "ctrl+x"]
delete = ["d", "delete"]
rename = ["r", "f2"]
new = ["ctrl+n", "a"]
# cannot use ctrl+shift+n even with kitty, because
# it is used by the terminal to open a new window
bulk_create = ["N", "A"]
zip = ["E"]
unzip = ["ctrl+e"]
# id love to use ctrl+shift+c
# but that is taken by terminals
up = ["up", "k"]
down = ["down", "j"]
up_tree = ["left", "h"]
down_tree = ["right", "l", "enter"]
bypass_up_tree = ["H"]
bypass_down_tree = ["L"]
page_up = ["pageup", "ctrl+b"]
page_down = ["pagedown", "ctrl+f"]
home = ["home", "g"]
end = ["end", "G"]
hist_previous = ["backspace", "u"]
# personal preference
hist_next = ["space"]
toggle_visual = ["v"]
toggle_all = ["%", "ctrl+a"]
toggle_hidden_files = ["full_stop"]
# similar to Midnight Commander / Norton Commander
toggle_select_item = ["insert"]
select_up = ["shift+up", "K"]
select_down = ["shift+down", "J"]
select_page_up = ["shift+pageup"]
select_page_down = ["shift+pagedown"]
select_home = ["shift+home"]
select_end = ["shift+end"]
tab_next = ["ctrl+j"]
tab_previous = ["ctrl+k"]
tab_new = ["n"]
tab_close = ["w"]
show_keybinds = ["?"]
quit_app = ["q", "ctrl+q"]
command_palette = "ctrl+p"
suspend_process = ["ctrl+z"]
open = ["o"]
open_editor = ["e"]
show_shell_screen = [">"]
open_right_click_menu = ["shift+f10"]
# unavailable for now
preview_select_left = []
preview_select_right = []
preview_scroll_left = []
preview_scroll_right = []
[keybinds.extra_copy]
open_popup = ["Y"]
copy_to_rovr = ["y"]
copy_highlighted = ["p"]
copy_name = ["n"]
copy_to_system_clip = ["s"]
copy_current_directory = ["d"]
[keybinds.change_sort_order]
open_popup = [","]
name = ["a"]
extension = ["e"]
natural = ["n"]
size = ["s"]
created = ["c"]
modified = ["m"]
descending = ["d"]
[keybinds.delete_files]
trash = ["d"]
delete = ["x"]
cancel = ["c", "escape"]
[keybinds.trash]
restore = ["r"]
purge = ["x"]
empty = ["E"]
cancel = ["c", "escape"]
[keybinds.filename_conflict]
overwrite = ["o"]
skip = ["s"]
rename = ["r"]
cancel = ["c", "escape"]
dont_ask_again = ["a"]
[keybinds.file_in_use]
retry = ["r"]
skip = ["s"]
cancel = ["c", "escape"]
dont_ask_again = ["a"]
[keybinds.filter_modal]
exit = ["escape"]
down = ["down", "ctrl+j"]
up = ["up", "ctrl+k"]
page_up = ["pageup", "ctrl+b"]
page_down = ["pagedown", "ctrl+f"]
[keybinds.yes_or_no]
yes = ["y"]
no = ["n", "escape"]
dont_ask_again = ["a"]
[keybinds.drag_and_drop]
copy = ["c"]
move = ["m"]
cancel = ["escape"]

[plugins.zoxide]
enabled = true
keybinds = ["z"]
show_scores = false

[plugins.bat]
enabled = false
executable = "bat"

[plugins.fd]
enabled = true
keybinds = ["f"]
executable = "fd"
relative_paths = true
follow_symlinks = false
no_ignore_parent = false
search_hidden = false
default_filter_types = ["file", "directory"]
timeout = 15

[plugins.rg]
enabled = true
keybinds = ["\\"]
executable = "rg"
case_sensitive = true
no_ignore_parent = false
follow_symlinks = false
search_hidden = false
timeout = 60

[plugins.poppler]
enabled = true
threads = 1
use_pdftocairo = false
poppler_folder = ""
pdf_batch_size = 2

[plugins.file_one]
enabled = false
get_description = true
